name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'adriaanvanrossum'
          reponame: 'kuipervanrossum.nl'
          cname: 'www.kuipervanrossum.nl'
          useyarn: false
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
