name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build Vue
        run: |
              npm ci
              npm run build
              cd dist
              ln -s index.html 404.html
              echo 'www.kuipervanrossum.nl' > CNAME
              git config --global user.email "ci@kuipervanrossum.nl"
              git config --global user.name "GitHub CI"
              git init
              git add -A
              git commit -m 'Automated build and deploy'
              git push -f https://adriaanvanrossum:${{ secrets.GITHUB_TOKEN }}@github.com/adriaanvanrossum/kuipervanrossum.nl.git main:gh-pages
        shell: bash
